INSERT INTO roles(name) VALUES ('ADMIN');
INSERT INTO roles(name) VALUES ('USER');

INSERT INTO users(email, password, first_name, last_name, date_of_birth, nationality, phone_no, pps_no, verified_email) VALUES ('admin@findmyroom.ie', '$2a$10$e1IP1zi1teM8y8TdiIXcy.osTx5/qXia4fNVS1JybrATi/QxIhUue', 'Admin', 'FMR', '01/01/1989', 'Italian','+353 98 765 4321', 'ADM1N12345', true);

INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('12 Parnell Street', 'D1 1234', 'Single-Room', false, true, false);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('24 Cork Rd', 'D15 2345', 'Double-Room', true, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('34 Dame Street', 'D2 2345', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('56 St. Patrick Avenue', 'D8 3456', 'Single-Room', false, true, false);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('78 Guinness St', 'D8 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('13 Kildare Road', '12 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('57 Drimnagh St', '12 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('88 Terenure Lane', '12 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('09 Ballymount Square', 'D24 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('38 Rathmines Square', 'D6 4567', 'Single-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('02 Donnybrook Road', 'D4 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('23 Ballsbridge Avenue', 'D4 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('06 Mountjoy Square', 'D7 4567', 'Shared-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('44 Phibsborough Avenue', 'D7 4567', 'Single-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('108 Botanic Rd', 'D09 4567', 'Double-Room', false, true, true);
INSERT INTO rooms(street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) VALUES ('07 Blackrock Lane', 'A94 4567', 'Shared-Room', false, true, true);

insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('024 Farwell Way', 'FR-N', 'Single-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('69420 Hauk Park', 'US-MN', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('5213 Coleman Junction', 'VE-M', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('537 Derek Trail', 'HN-CP', 'Single-Room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('413 Columbus Crossing', 'BR-SP', 'Double-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('36 Morning Terrace', 'LY-TB', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('3900 Truax Park', 'PG-SHM', 'Shared-room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('5833 Westridge Avenue', 'BO-S', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('5 Johnson Trail', 'US-CA', 'Double-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('349 Leroy Park', 'BT-33', 'Single-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('366 Grim Court', 'CL-LL', 'Double-Room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('23529 Homewood Court', 'GB-ENG', 'Single-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('606 Armistice Plaza', 'FR-J', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('199 Knutson Drive', 'PR-U-A', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('33549 Towne Lane', 'GA-8', 'Single-Room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('257 Hanson Lane', 'MX-CHH', 'Shared-room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('03261 Forest Dale Center', 'BR-SP', 'Single-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('594 Bartillon Crossing', 'US-AR', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('282 Green Ridge Plaza', 'US-OK', 'Double-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('5566 John Wall Lane', 'SE-AC', 'Single-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('88408 Fulton Pass', 'US-CO', 'Shared-room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('32 Weeping Birch Park', 'MK-003', 'Double-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('0013 Ridgeview Hill', 'US-AZ', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('77 Larry Circle', 'CI-10', 'Shared-room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('061 Upham Circle', 'IT-34', 'Single-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('02 Hovde Park', 'US-WI', 'Shared-room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('356 Dawn Center', 'PH-AUR', 'Double-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('0 Di Loreto Road', 'US-IA', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('0 Ilene Road', 'NZ-WKO', 'Shared-room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('7 Saint Paul Court', 'ME-16', 'Single-Room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('848 Springs Park', 'US-TX', 'Single-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('53 Marcy Park', 'AU-QLD', 'Single-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('215 Northport Drive', 'US-FL', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('75248 Myrtle Hill', 'US-NY', 'Single-Room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('4 Shelley Way', 'US-MA', 'Single-Room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('6620 Esch Trail', 'ID-PA', 'Single-Room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('9 American Ash Parkway', 'BR-MG', 'Double-Room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('45896 Mccormick Terrace', 'CA-ON', 'Shared-room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('6 Bartillon Drive', 'US-WV', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('6908 Evergreen Junction', 'FR-J', 'Double-Room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('38146 Prairie Rose Terrace', 'GY-BA', 'Shared-room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('905 Katie Court', 'PK-PB', 'Shared-room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('2 Melvin Plaza', 'BS-HR', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('1044 Gale Plaza', 'AU-QLD', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('6 Kenwood Junction', 'FR-J', 'Single-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('0 Clarendon Alley', 'ID-PA', 'Double-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('8204 Stoughton Crossing', 'AU-QLD', 'Double-Room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('69 Rigney Way', 'TR-50', 'Double-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('8791 Northland Pass', 'US-OR', 'Single-Room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('779 Russell Place', 'US-AK', 'Shared-room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('494 Daystar Pass', 'AU-WA', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('21251 Walton Hill', 'FR-I', 'Double-Room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('32133 Ronald Regan Point', 'US-WA', 'Shared-room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('90 Parkside Drive', 'CA-NT', 'Shared-room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('48679 Prentice Drive', 'MH-MIL', 'Shared-room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('1 Ruskin Junction', 'CA-MB', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('413 Debs Trail', 'BR-MG', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('6 Roxbury Trail', 'US-NV', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('472 Northridge Center', 'KR-42', 'Shared-room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('2658 Basil Parkway', 'IN-UP', 'Single-Room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('4 Graedel Parkway', 'GY-BA', 'Single-Room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('394 Algoma Pass', 'VU-PAM', 'Shared-room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('0 New Castle Court', 'BR-RJ', 'Single-Room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('66 Maywood Park', 'PF-U-A', 'Single-Room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('33 Claremont Hill', 'CA-AB', 'Single-Room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('5105 Ridge Oak Alley', 'GR-04', 'Double-Room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('8914 Roxbury Alley', 'BR-TO', 'Double-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('1948 Truax Park', 'RU-SA', 'Single-Room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('8 Northview Road', 'US-MT', 'Single-Room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('13725 Luster Way', 'PG-ESW', 'Shared-room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('070 Becker Hill', 'US-MI', 'Double-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('20025 Cordelia Place', 'IT-36', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('55 Orin Crossing', 'US-AK', 'Shared-room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('917 Ridgeview Point', 'NZ-WKO', 'Shared-room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('91 Mayer Alley', 'PA-8', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('76159 Acker Hill', 'US-MN', 'Double-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('08778 Sundown Hill', 'VE-F', 'Single-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('246 Caliangt Circle', 'US-AK', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('167 John Wall Park', 'BR-MG', 'Shared-room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('7 Macpherson Plaza', 'SA-06', 'Shared-room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('1233 Bellgrove Crossing', 'PF-U-A', 'Shared-room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('337 Canary Pass', 'US-AK', 'Single-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('9458 Vernon Crossing', 'US-SC', 'Single-Room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('9692 Blue Bill Park Avenue', 'JP-01', 'Double-Room', false, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('5 Roxbury Drive', 'OM-ZU', 'Double-Room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('292 Marcy Parkway', 'DE-ST', 'Shared-room', true, true, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('87407 Heath Junction', 'MX-TAM', 'Shared-room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('8 Green Ridge Avenue', 'ZA-WC', 'Single-Room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('065 Esch Park', 'CN-45', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('08 Golf View Trail', 'PG-MPL', 'Single-Room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('04058 Hanover Alley', 'US-CA', 'Single-Room', false, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('36328 Carberry Plaza', 'GB-ENG', 'Shared-room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('32 Northfield Circle', 'US-OR', 'Single-Room', true, true, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('3 Del Sol Hill', 'IN-AR', 'Double-Room', true, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('4284 Ridgeview Terrace', 'TD-CB', 'Double-Room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('70881 Grasskamp Terrace', 'CA-ON', 'Shared-room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('98322 Debs Crossing', 'US-TX', 'Single-Room', false, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('7 Randy Avenue', 'US-IL', 'Shared-room', false, false, false);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('83 Warrior Trail', 'US-AK', 'Single-Room', true, false, true);
insert into rooms (street_address, eir_code, room_type, ensuite_bathroom, heating, carpeted) values ('3 Judy Avenue', 'CA-BC', 'Shared-room', false, false, true);


insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1204, false, false, false, false, true, false, true, '2022-05-07', 1, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1205, false, false, false, false, false, false, false, '2022-06-24', 2, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1470, false, false, false, true, false, true, false, '2022-05-14', 3, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3878, false, true, true, false, true, false, false, '2021-12-25', 4, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1592, true, false, false, false, true, false, false, '2022-07-03', 5, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2639, false, false, true, false, false, false, false, '2022-07-04', 6, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1429, false, false, false, true, true, false, false, '2022-12-07', 7, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2364, true, true, true, false, false, true, true, '2021-12-18', 8, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2251, false, false, true, false, false, true, false, '2022-04-18', 9, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2290, false, false, true, false, false, false, true, '2022-10-29', 10, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1471, false, false, false, false, false, true, false, '2022-11-26', 11, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (768, true, false, true, true, true, false, false, '2022-03-19', 12, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2510, false, true, false, false, false, false, false, '2022-08-06', 13, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1753, true, true, false, false, true, true, false, '2022-10-19', 14, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (550, true, false, true, false, false, true, false, '2022-01-25', 15, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1094, true, true, true, false, true, false, false, '2022-05-06', 16, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (637, false, false, true, false, false, true, true, '2022-10-28', 17, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3274, false, false, true, false, true, false, false, '2022-10-16', 18, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2847, true, true, true, false, true, true, false, '2022-03-06', 19, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3406, true, true, false, true, false, true, false, '2022-09-03', 20, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3513, true, false, true, true, false, false, false, '2022-03-04', 21, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2565, false, true, false, false, true, true, true, '2022-08-03', 22, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1891, false, true, true, false, false, false, false, '2022-09-15', 23, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1171, true, false, true, true, false, true, true, '2022-01-17', 24, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3835, true, true, false, true, false, true, false, '2022-06-04', 25, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2650, false, true, true, false, false, true, true, '2022-02-28', 26, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3753, false, true, true, false, true, false, false, '2022-01-29', 27, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3626, false, true, false, true, true, false, false, '2022-04-23', 28, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1174, false, false, false, true, true, false, false, '2021-12-24', 29, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2030, false, false, false, false, true, false, false, '2022-06-24', 30, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3392, false, true, true, false, true, false, false, '2022-09-17', 31, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (695, false, false, true, true, false, true, true, '2022-08-13', 32, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2888, false, false, false, false, false, true, false, '2022-08-26', 33, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2219, true, false, true, true, true, true, false, '2022-05-03', 34, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1743, false, false, false, false, true, true, false, '2022-09-19', 35, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1075, false, true, true, false, false, false, false, '2022-03-20', 36, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1693, true, true, true, false, true, true, false, '2022-08-31', 37, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1757, false, true, false, false, true, false, true, '2022-07-10', 38, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (646, true, true, false, true, true, true, true, '2022-04-16', 39, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3666, false, false, false, true, false, false, false, '2022-06-15', 40, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3058, true, true, true, false, false, false, false, '2022-06-03', 41, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2476, true, true, true, false, false, true, false, '2022-03-14', 42, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1581, false, false, true, false, false, false, true, '2022-06-12', 43, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2088, true, true, false, true, false, false, true, '2022-12-01', 44, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (627, true, true, false, false, false, false, false, '2022-11-25', 45, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3890, true, true, false, false, false, true, false, '2022-01-05', 46, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1987, true, true, false, true, true, false, true, '2022-07-05', 47, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2543, false, true, false, false, true, false, true, '2022-09-29', 48, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2062, true, false, false, false, false, false, false, '2022-10-13', 49, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1358, true, true, false, false, true, false, false, '2022-07-04', 50, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (862, true, true, true, false, true, true, false, '2021-12-26', 51, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1600, false, false, true, true, false, true, false, '2022-06-18', 52, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2342, true, true, false, true, false, false, false, '2022-08-22', 53, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1163, false, true, true, false, false, true, true, '2022-10-27', 54, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (619, false, true, true, true, true, true, true, '2021-12-21', 55, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1713, false, true, true, false, false, true, false, '2021-12-30', 56, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (630, false, true, false, false, false, true, false, '2022-10-16', 57, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3909, false, true, true, false, false, false, true, '2022-09-26', 58, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2887, false, true, false, false, true, false, true, '2022-08-26', 59, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1081, true, false, true, false, true, true, false, '2022-02-28', 60, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (799, true, true, true, false, false, true, false, '2022-05-12', 61, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1471, false, true, true, false, false, true, true, '2022-01-28', 62, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (499, true, true, false, false, false, true, false, '2022-03-25', 63, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3766, false, false, true, false, true, true, true, '2022-05-13', 64, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1483, false, true, false, true, false, false, true, '2022-09-15', 65, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1599, false, true, false, false, true, true, true, '2022-07-24', 66, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3983, true, false, true, true, false, false, false, '2022-05-31', 67, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1897, false, false, true, true, false, false, true, '2022-10-18', 68, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2521, true, true, false, true, false, false, true, '2022-09-18', 69, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3260, false, false, false, true, true, false, true, '2022-08-31', 70, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (862, false, false, true, false, false, true, false, '2022-10-01', 71, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2822, true, false, false, true, true, true, false, '2022-05-05', 72, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2255, true, false, true, true, true, false, true, '2022-12-08', 73, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2859, false, true, true, false, true, true, false, '2022-09-13', 74, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2921, true, true, false, true, true, true, false, '2022-02-26', 75, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3986, false, false, false, false, false, false, true, '2022-12-09', 76, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (501, true, true, true, false, true, true, true, '2022-08-22', 77, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2420, false, false, false, false, false, true, false, '2022-12-04', 78, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1107, true, false, false, false, true, false, false, '2022-03-31', 79, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3879, false, false, true, false, false, true, true, '2022-02-14', 80, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2277, true, true, false, true, false, true, true, '2022-08-01', 81, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1768, true, true, false, true, false, false, false, '2022-10-13', 82, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1910, false, true, false, false, true, false, true, '2022-11-30', 83, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (497, false, true, false, true, false, false, true, '2022-02-08', 84, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (545, false, true, false, true, true, false, false, '2022-09-09', 85, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1033, false, true, false, true, true, true, false, '2022-09-12', 86, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (467, false, true, true, true, false, true, true, '2022-07-27', 87, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (729, true, false, false, false, false, false, false, '2022-06-20', 88, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1001, false, false, true, false, false, true, false, '2022-05-15', 89, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2698, false, true, true, true, true, false, true, '2022-08-17', 90, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2253, true, false, true, false, false, true, true, '2022-07-08', 91, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3195, false, true, false, true, true, true, true, '2022-10-14', 92, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1920, false, false, false, true, true, true, false, '2022-10-29', 93, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2303, true, false, false, false, true, true, true, '2022-10-22', 94, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (3640, false, false, false, false, false, true, true, '2022-09-15', 95, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1413, true, true, false, false, false, false, true, '2022-03-03', 96, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2706, false, true, true, false, false, true, true, '2022-11-16', 97, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (2554, false, true, true, true, false, false, true, '2022-05-12', 98, 1);
insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (1866, false, true, true, true, true, true, false, '2022-10-18', 99, 1);

insert into ads (rent, bills_included, owner_occupied, parking, pet_allowed, washing_machine, dryer, dish_washer, created_at, room_id, user_id) values (597, false, false, false, false, true, false, false, '2022-04-15', 100, 1);

